#include "objects.h"

#ifndef RESERVED_H
#define RESERVED_H

typedef enum reserved_id_code {
    RESERVED_ID_CODE_NULL,
    RESERVED_ID_CODE_INPUT,
    RESERVED_ID_CODE_OUTPUT,
    RESERVED_ID_CODE_ERROR,
    RESERVED_ID_CODE_IS_NUMBER,
    RESERVED_ID_CODE_IS_CALLABLE,
    RESERVED_ID_CODE_IS_PAIR,
    RESERVED_ID_CODE_DEBUG,
    RESERVED_ID_CODE_END_OF_ENUM
} reserved_id_name_enum;

#define RESERVED_ID_COUNT RESERVED_ID_CODE_END_OF_ENUM

extern const char* RESERVED_IDS[RESERVED_ID_COUNT];

extern const object_t RESERVED_OBJS[RESERVED_ID_COUNT];
extern const object_t* NULL_OBJECT_PTR;

#endif
